use silfae;

SELECT COUNT(*) as total FROM FarrDarmsPagos 
WHERE NR_GUIA = 15206 
AND AA_EXERCICIO = 2025
AND CD_BANCO = 70
AND NR_BDA = 37
AND NR_COMPLEMENTO = 0
AND NR_LOTE_NSA = 730
AND TP_LOTE_D = 1;